---
title: "PESA body mass changes"
date: "`r format(Sys.time(), '%d %B, %Y')`"
format: 
  html:
    toc: true
    code-fold: true
    code-tools: true
    self-contained: true
execute:
  warning: false
---

```{r, settings_data}
source("R/DAT/wrangle_datasets.R")
```


## EDA on body mass
```{r}

ggplot(cap, aes(y = weight, x = factor(year_)) ) + 
geom_boxplot()

ggplot(cap, aes(y = weight, x = capture_id, group = ID) ) + 
facet_wrap(~year_) + 
geom_smooth(method = lm, se = FALSE)


ggplot(wcap, aes(delta_weight)) +
  geom_histogram()

ggplot(wcap, aes(y = delta_weight, x = delta_time) ) +
  geom_point() + 
  geom_smooth()


```

## Paternity

### Paternity and body mass
Subset of males that sired at least one young

```{r}
x = merge(cap, pat, by = c("ID", "year_"))

ggplot(x, aes(y = N_females, x = weight)) +
  geom_point() 

glmmTMB(N_females ~ weight + (1|year_), family = poisson, x) |>
tbl_regression(intercept = TRUE)


ggplot(x, aes(y = N_young, x = weight)) +
  geom_point() 

glmmTMB(N_young ~ weight + (1|year_), family = poisson, x) |>
tbl_regression(intercept = TRUE)

```

### Paternity and body mass
All males


```{r}
#using first capture
x = merge(cap, pat, by = c("ID", "year_"), all.x = TRUE)
x[is.na(N_females), N_females := 0]
x[is.na(N_young), N_young := 0]


ggplot(x, aes(y = N_females, x = weight)) +
  geom_point() 

glmmTMB(N_females ~ weight + (1|year_), zi=~weight, family = poisson, x) |>
tbl_regression(intercept = TRUE)


ggplot(x, aes(y = N_young, x = weight)) +
  geom_point() 

glmmTMB(N_young ~ weight + (1|year_), zi=~weight, family = poisson, x) |>
tbl_regression(intercept = TRUE)

```




### Paternity and tenure


```{r}
x <- merge(cap, pat, by = c("ID", "year_"), all.x = TRUE)
x[is.na(N_females), N_females := 0]
x[is.na(N_young), N_young := 0]

x = merge(x, ten, by= c('ID', "year_"))


fm = glmmTMB(N_females ~ tenureDays + (1|year_), family = poisson, x)

tbl_regression(fm , intercept = TRUE)

ggeffect(fm) |> plot()


fm = glmmTMB(N_young ~ tenureDays + (1|year_), family = poisson, x)
tbl_regression(fm, intercept = TRUE)

ggeffect(fm) |> plot()


```


### Paternity, tenure and body mass


```{r}
x <- merge(cap, pat, by = c("ID", "year_"), all.x = TRUE)
x[is.na(N_females), N_females := 0]
x[is.na(N_young), N_young := 0]

x = merge(x, ten, by= c('ID', "year_"))


fm = glmmTMB(N_females ~ weight + tenureDays + (1|year_), family = poisson, x)

tbl_regression(fm , intercept = TRUE)

g1 = ggeffect(fm, "weight") |> plot()
g2 = ggeffect(fm, "tenureDays") |> plot()

g1 + g2


fm = glmmTMB(N_young ~ weight + tenureDays + (1 | year_), family = poisson, x)
tbl_regression(fm, intercept = TRUE)

g1 <- ggeffect(fm, "weight") |> plot()
g2 <- ggeffect(fm, "tenureDays") |> plot()

g1 + g2


```

### Paternity and body mass change

```{r}
x = merge(wcap, pat, by = c("ID", "year_"))
x = merge(x, ten, by = c("ID", "year_"))

ggplot(x, aes(y = N_young, x = delta_weight)) +
  geom_point() +
  geom_smooth(method = lm)

glm(N_young ~ weight_1 + delta_weight, poisson, x) |>
tbl_regression(intercept = TRUE)

glm(N_young ~ tenureDays + weight_1 + delta_weight, poisson, x) |>
tbl_regression(intercept = TRUE)






```
